steps:
- task: Npm@1
  displayName: 'Build and Test'
  inputs:
    command: custom
    customCommand: run ci-build
  env:
    SERVICE_PRINCIPAL_CLIENT_ID: $(SERVICE_PRINCIPAL_CLIENT_ID)
    SERVICE_PRINCIPAL_SECRET: $(SERVICE_PRINCIPAL_SECRET)
    SERVICE_PRINCIPAL_DOMAIN: $(SERVICE_PRINCIPAL_DOMAIN)
    DISPLAY: :10 # Only necessary for linux tests
    DOCKER_UNAVAILABLE: ${{ parameters.dockerUnavailable }}
