steps:
- task: Npm@1
  displayName: 'Build, Test, and Package'
  inputs:
    command: custom
    customCommand: run ci-package
  env:
    SERVICE_PRINCIPAL_CLIENT_ID: $(SERVICE_PRINCIPAL_CLIENT_ID)
    SERVICE_PRINCIPAL_SECRET: $(SERVICE_PRINCIPAL_SECRET)
    SERVICE_PRINCIPAL_DOMAIN: $(SERVICE_PRINCIPAL_DOMAIN)
    DISPLAY: :10 # Only necessary for linux tests
    DOCKER_UNAVAILABLE: ${{ parameters.dockerUnavailable }}

- task: CopyFiles@2
  displayName: 'Copy vsix to staging directory'
  inputs:
    Contents: '**/*.vsix'
    TargetFolder: '$(build.artifactstagingdirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish artifacts: vsix'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
    ArtifactName: vsix
  condition: ne(variables['System.PullRequest.IsFork'], 'True')
