# Trigger the build whenever `main` is updated
trigger:
  - main

# Grab the base templates from https://github.com/microsoft/vscode-azuretools
resources:
  repositories:
    - repository: templates
      type: github
      name: microsoft/vscode-azuretools
      ref: bmw/pipelines # TODO: update to main
      endpoint: GitHub

# Use those templates
extends:
  template: azure-pipelines/main.yml@templates
