trigger:
  - main
  - bmw/pipelines # todo

resources:
  repositories:
    - repository: templates
      type: github
      name: microsoft/vscode-azuretools
      ref: bmw/pipelines
      endpoint: GitHub

extends:
  template: azure-pipelines/main.yml@templates
