resources:
  repositories:
    - repository: templates
      type: github
      name: microsoft/vscode-azuretools
      ref: bmw/pipelines
      endpoint: GitHub

extends:
  template: azure-pipelines/main@templates
