name: Node PR Lint, Build and Test

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - rel/*
  pull_request:
    branches:
      - main
      - rel/*

jobs:
  Build:
    uses: microsoft/vscode-azuretools/.github/workflows/main.yml@bmw/ghpipelines
