name: Node CI Build and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build_and_test:
    uses: microsoft/vscode-azuretools/.github/workflows/main.yml@bmw/ghpipelines
