name: Node PR Lint, Build and Test

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  Build:
    uses: microsoft/vscode-azuretools/.github/workflows/main.yml@bmw/ghpipelines
